services:

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  #pgSQL Service
  db:
    image: postgres:13
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: newbase
      PGDATA: /var/lib/postgresql/data
      SERVICE_TAGS: dev
      SERVICE_NAME: postgresql
    volumes:
      - ./docker/pgsql:/var/lib/postgresql/data

  #pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: test@gmail.com
        PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - "8080:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json